version: '3.7'

services:
  hadoop:
    build: .
    container_name: hadoop
    hostname: hadoop
    ports:
      - "9870:9870"   # Namenode Web UI
      - "8088:8088"   # YARN Web UI
      - "9864:9864"   # Datanode Web UI
      - "9866:9866"   # Datanode IPC
      - "9000:9000"   # HDFS
      - "22:22"       # SSH
    volumes:
      - ./data:/opt/hadoop/data
      - ./logs:/opt/hadoop/logs
    networks:
      hadoop-net:
        aliases:
          - hadoop
    environment:
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - HDFS_JOURNALNODE_USER=root
      - HDFS_ZKFC_USER=root
      - YARN_RESOURCEMANAGER_USER=root
      - YARN_NODEMANAGER_USER=root


networks:
  hadoop-net:
    driver: bridge