version: '3.7'

services:
  namenode:
    build: .
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"   # Namenode Web UI
      - "8088:8088"   # YARN Web UI
      - "9000:9000"   # HDFS
      - "22:22"       # SSH
    volumes:
      - namenode-data:/opt/hadoop/data/namenode
      - ./logs:/opt/hadoop/logs
    networks:
      hadoop-net:
        aliases:
          - namenode
    environment:
      - HDFS_NAMENODE_USER=root
      - YARN_RESOURCEMANAGER_USER=root
      - CLUSTER_MODE=multi

  datanode1:
    build: .
    container_name: datanode1
    hostname: datanode1
    volumes:
      - datanode1-data:/opt/hadoop/data/datanode
    networks:
      hadoop-net:
    depends_on:
      - namenode
    environment:
      - HDFS_DATANODE_USER=root
      - YARN_NODEMANAGER_USER=root
      - CLUSTER_MODE=multi

  datanode2:
    build: .
    container_name: datanode2
    hostname: datanode2
    volumes:
      - datanode2-data:/opt/hadoop/data/datanode
    networks:
      hadoop-net:
    depends_on:
      - namenode
    environment:
      - HDFS_DATANODE_USER=root
      - YARN_NODEMANAGER_USER=root
      - CLUSTER_MODE=multi

  datanode3:
    build: .
    container_name: datanode3
    hostname: datanode3
    volumes:
      - datanode3-data:/opt/hadoop/data/datanode
    networks:
      hadoop-net:
    depends_on:
      - namenode
    environment:
      - HDFS_DATANODE_USER=root
      - YARN_NODEMANAGER_USER=root
      - CLUSTER_MODE=multi

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:
  datanode3-data:

networks:
  hadoop-net:
    driver: bridge